// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/proto/pingpong.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingPonger_PingPong_FullMethodName = "/PingPonger/PingPong"
)

// PingPongerClient is the client API for PingPonger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingPongerClient interface {
	PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type pingPongerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingPongerClient(cc grpc.ClientConnInterface) PingPongerClient {
	return &pingPongerClient{cc}
}

func (c *pingPongerClient) PingPong(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, PingPonger_PingPong_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingPongerServer is the server API for PingPonger service.
// All implementations must embed UnimplementedPingPongerServer
// for forward compatibility.
type PingPongerServer interface {
	PingPong(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedPingPongerServer()
}

// UnimplementedPingPongerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingPongerServer struct{}

func (UnimplementedPingPongerServer) PingPong(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingPong not implemented")
}
func (UnimplementedPingPongerServer) mustEmbedUnimplementedPingPongerServer() {}
func (UnimplementedPingPongerServer) testEmbeddedByValue()                    {}

// UnsafePingPongerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingPongerServer will
// result in compilation errors.
type UnsafePingPongerServer interface {
	mustEmbedUnimplementedPingPongerServer()
}

func RegisterPingPongerServer(s grpc.ServiceRegistrar, srv PingPongerServer) {
	// If the following call pancis, it indicates UnimplementedPingPongerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingPonger_ServiceDesc, srv)
}

func _PingPonger_PingPong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongerServer).PingPong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingPonger_PingPong_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongerServer).PingPong(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PingPonger_ServiceDesc is the grpc.ServiceDesc for PingPonger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingPonger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PingPonger",
	HandlerType: (*PingPongerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingPong",
			Handler:    _PingPonger_PingPong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/pingpong.proto",
}
