// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/pingpong.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_pingpong_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pingpong_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pingpong_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_internal_proto_pingpong_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pingpong_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pingpong_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_internal_proto_pingpong_proto protoreflect.FileDescriptor

const file_internal_proto_pingpong_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/pingpong.proto\"\x1f\n" +
	"\vPingRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\" \n" +
	"\fPongResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg25\n" +
	"\n" +
	"PingPonger\x12'\n" +
	"\bPingPong\x12\f.PingRequest\x1a\r.PongResponseB4Z2github.com/vsespontanno/gochat-grpc/internal/protob\x06proto3"

var (
	file_internal_proto_pingpong_proto_rawDescOnce sync.Once
	file_internal_proto_pingpong_proto_rawDescData []byte
)

func file_internal_proto_pingpong_proto_rawDescGZIP() []byte {
	file_internal_proto_pingpong_proto_rawDescOnce.Do(func() {
		file_internal_proto_pingpong_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_pingpong_proto_rawDesc), len(file_internal_proto_pingpong_proto_rawDesc)))
	})
	return file_internal_proto_pingpong_proto_rawDescData
}

var file_internal_proto_pingpong_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_pingpong_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: PingRequest
	(*PongResponse)(nil), // 1: PongResponse
}
var file_internal_proto_pingpong_proto_depIdxs = []int32{
	0, // 0: PingPonger.PingPong:input_type -> PingRequest
	1, // 1: PingPonger.PingPong:output_type -> PongResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_pingpong_proto_init() }
func file_internal_proto_pingpong_proto_init() {
	if File_internal_proto_pingpong_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_pingpong_proto_rawDesc), len(file_internal_proto_pingpong_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_pingpong_proto_goTypes,
		DependencyIndexes: file_internal_proto_pingpong_proto_depIdxs,
		MessageInfos:      file_internal_proto_pingpong_proto_msgTypes,
	}.Build()
	File_internal_proto_pingpong_proto = out.File
	file_internal_proto_pingpong_proto_goTypes = nil
	file_internal_proto_pingpong_proto_depIdxs = nil
}
